version: '3.9'
x-customer-integrations:
  licensing: 
    licenseExpirationInDays: 7
    productTierSku: 'PRODUCT-DEV-SKU'
  
services:
  web:
    image: ghcr.io/omnistrate-community/licensing-example-go:0.0.7
    ports:
      - '80:80'
      # - '443:443'
    environment:
      - SECURITY_CONTEXT_USER_ID=2000
      - SECURITY_CONTEXT_GROUP_ID=1000
